### ISSUE TITLE
Generated JsonAdapter.Factory doesn't handle nulls

### ISSUE THREAD

**Issue by ktchernov** [rharter/auto-value-moshi#25]
If a class that uses the generated `typeAdapterFactory` ends up having a `null` value in the JSON, parsing fails with:

```
com.squareup.moshi.JsonDataException: Expected BEGIN_OBJECT but was NULL at path $.data
at com.squareup.moshi.JsonReader.beginObject(JsonReader.java:383)
at io.github.ktchernov.moshiautovaluebug.AutoValue_TestClassA_TestClassB$AutoValue_TestClassBJsonAdapter.fromJson(AutoValue_TestClassA_TestClassB.java:39)
at io.github.ktchernov.moshiautovaluebug.AutoValue_TestClassA_TestClassB$AutoValue_TestClassBJsonAdapter.fromJson(AutoValue_TestClassA_TestClassB.java:32)
at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:183)
at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:144)
at com.squareup.moshi.JsonAdapter$1.fromJson(JsonAdapter.java:68)
at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:33)
at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:37)
at io.github.ktchernov.moshiautovaluebug.MoshiAutoValueTest.parseWithNull(MoshiAutoValueTest.java:33)
....
```

What should happen, is that `null` should be parsed as a `null` object.

I've created a gist with a sample class and a unit test here: https://gist.github.com/ktchernov/cd3520cebf8aa56214b5155a648d38d4

The first unit test `parseValid()` passes as expected, the second test `parseWithNull()` fails with the above exception.

**Comment by ktchernov** [comment]
I worked around this by implementing a:

```
private static JsonAdapter.Factory nullSafe(JsonAdapter.Factory wrappedFactory) {
    return (type, annotations, moshi) -> {
        JsonAdapter<?> jsonAdapter = wrappedFactory.create(type, annotations, moshi);
        if (jsonAdapter != null) {
            return jsonAdapter.nullSafe();
        }
        return null;
    };
}
```

And then when adding the factory to Moshi:

```
new Moshi.Builder().add(nullSafe(SomeClass.typeAdapterFactory())).build();
```

**Comment by ZacSweers** [comment]
Actually, would this be covered by the fix in https://github.com/rharter/auto-value-moshi/pull/28?

**Comment by rharter** [comment]
I don't think so.  We'll need to either add `nullSafe()` to the adapter calls, or check for null.  I'm onsite at a client so I can't get to it until tonight.

**Comment by ZacSweers** [comment]
ping :)
